# Use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

language: scala

jdk:
  - oraclejdk8

matrix:
  fast_finish: true

env:
  matrix:
    - SBT_CMD=";test:compile;scalafmtCheck"
    - SBT_CMD="mimaReportBinaryIssues"
    - SBT_CMD="safeUnitTests"
    - SBT_CMD="otherUnitTests"
    - SBT_CMD="scripted actions/*"
    - SBT_CMD="scripted apiinfo/*"
    - SBT_CMD="scripted compiler-project/*"
    - SBT_CMD="scripted dependency-management/*1of4"
    - SBT_CMD="scripted dependency-management/*2of4"
    - SBT_CMD="scripted dependency-management/*3of4"
    - SBT_CMD="scripted dependency-management/*4of4"
    - SBT_CMD="scripted ivy-deps-management/*"
    - SBT_CMD="scripted java/*"
    - SBT_CMD="scripted package/*"
    - SBT_CMD="scripted project/*1of2"
    - SBT_CMD="scripted project/*2of2"
    - SBT_CMD="scripted reporter/*"
    - SBT_CMD="scripted run/*"
    - SBT_CMD="scripted source-dependencies/*1of3"
    - SBT_CMD="scripted source-dependencies/*2of3"
    - SBT_CMD="scripted source-dependencies/*3of3"
    - SBT_CMD="scripted tests/*"
    - SBT_CMD="scripted project-load/*"
    - SBT_CMD="repoOverrideTest:scripted dependency-management/*"

notifications:
  email:
    - sbt-dev-bot@googlegroups.com

script:
  - sbt -J-XX:ReservedCodeCacheSize=128m -J-Xmx1g -J-Xms1g "$SBT_CMD"

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete
