dist: xenial
group: stable

language: scala

scala:
  - 2.12.8

env:
  global:
    - secure: D9Ckfxq/5n+41REwuPBwb0CHRVSPtCJRN+N1FWNFjUnfCHZQCeclP8Ydp9ql/fZxICG8rnCOI5XW0j2YeAiR+abpQNmQ42pKMEjNT0VQDZ0I1lQfiDL071Kj+ui9AH+TqAvBT011u72ML52iDfV0WaL/Skf1Noh0lXc+IscRI56OLRv+YU5n5aNZhXon6AZHU11rRCg4aMwaHr+U9ISSUXc6OtJeFC/SAYNUNYEOZwTOJ4Y2+VrKAmKuIZ2jjkMF13eKMzXw5g+u8V3AmOpIm1RiyS2dAgAoc+r2ucF9RUMsfiZIF0XBu65iv9hZP5m0q11n6IFEKC9bpLsTYCAwX2MgVayoHvDQv1gkL/cA1gkqmf0Kkx3oc33aYLgsCydj2Lbg/myKD+GeHxr5WhyeSEee3Bwj+KGNwvjfcaPEECCor6yilKGdIsuYbfHzu8B8moNjwH7ui5f5w/1xuWrdaSA23LOIYbhP+2rM894JIYNNt5vlMLoYMzmC9N1E/qyBRYSdfMr+Uh8qI+j85hkKKgEffSu9f55IH6bk6Lq08Nc4d64KXUISDNJj59MrJcadatsS2vp+u39zR/iIewW4a017bAFfv57AJb6SwLdvASG+psFH8MRPD6xYPZKNw4Al/4YMc+oXONplSXyOu/jQYjSfK9tyvJwpoY7tLh6vEBc=

matrix:
  include:
  - env:
      - ADOPTOPENJDK=11
  - env:
      - ADOPTOPENJDK=8

before_install:
  # adding $HOME/.sdkman to cache would create an empty directory, which interferes with the initial installation
  - "[[ -d $HOME/.sdkman/bin/ ]] || rm -rf $HOME/.sdkman/"
  - curl -sL https://get.sdkman.io | bash
  - echo sdkman_auto_answer=true > $HOME/.sdkman/etc/config
  - source "$HOME/.sdkman/bin/sdkman-init.sh"

install:
  - sdk install java $(sdk list java | grep -o "$ADOPTOPENJDK\.[0-9\.]*hs-adpt" | head -1)
  - bin/fixpreloaded.sh
  - unset JAVA_HOME
  - java -Xmx32m -version
  # detect sbt version from project/build.properties
  - export TRAVIS_SBT=$(grep sbt.version= project/build.properties | sed -e 's/sbt.version=//g' ) && echo "sbt $TRAVIS_SBT"
  # - export TRAVIS_SBT=1.3.3
  - sdk install sbt $TRAVIS_SBT
  # override Travis CI's SBT_OPTS
  - unset SBT_OPTS
  - export JAVA_OPTS="-Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M"

script: sbt -Dfile.encoding=UTF8
  ++$TRAVIS_SCALA_VERSION!
  mimaReportBinaryIssues
  scalafmtCheckAll
  whitesourceCheckPolicies
  test
  packagedArtifacts # ensure that all artifacts for publish package without failure

before_cache:
  # - find $HOME/.ivy2/local -name "*-LM-SNAPSHOT*" -exec rm -r "{}" \;
  - find $HOME/.ivy2/cache -name "*-LM-SNAPSHOT*" -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -delete
  - find $HOME/.sbt        -name "*.lock"               -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.sdkman
