os: linux

language: scala

matrix:
  include:
    - jdk: openjdk8
#    - jdk: openjdk11

before_install:
  - sudo apt-get update
  - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x

before_script:
 - export JVM_OPTS="-Dfile.encoding=UTF-8 -Xmx1G -Xms1G -server -XX:ReservedCodeCacheSize=128M"
 - unset _JAVA_OPTIONS

script: sbt scripted

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -delete
  - find $HOME/.sbt        -name "*.lock"               -delete
