language: scala
script:
  - sbt "scripted $SCRIPTED_TEST"
env:
  - SCRIPTED_TEST=actions/*
  - SCRIPTED_TEST=api/*
  - SCRIPTED_TEST=compiler-project/*
  - SCRIPTED_TEST=dependency-management/*
  - SCRIPTED_TEST=java/*
  - SCRIPTED_TEST=package/*
  - SCRIPTED_TEST=project/*
  - SCRIPTED_TEST=reporter/*
  - SCRIPTED_TEST=run/*
  - SCRIPTED_TEST=source-dependencies/*
  - SCRIPTED_TEST=tests/*
jdk:
  - openjdk6
notifications:
  email:
    - qbranch@typesafe.com
