dist: xenial

language: scala

env:
  global:
    - TRAVIS_JDK=adopt@1.11.0-1
    - SCALA_212=2.12.12
    - SCALA_213=2.13.1
    - UTIL_TESTS="utilCache/test;utilControl/test;utilInterface/test;utilLogging/test;utilPosition/test;utilRelation/test;utilScripted/test;utilTracking/test"
    # WHITESOURCE_PASSWORD=
    - secure: d3bu2KNwsVHwfhbGgO+gmRfDKBJhfICdCJFGWKf2w3Gv86AJZX9nuTYRxz0KtdvEHO5Xw8WTBZLPb2thSJqhw9OCm4J8TBAVqCP0ruUj4+aqBUFy4bVexQ6WKE6nWHs4JPzPk8c6uC1LG3hMuzlC8RGETXtL/n81Ef1u7NjyXjs=
  matrix:
    - SBT_CMD="mimaReportBinaryIssues ; javafmtCheck ; Test / javafmtCheck; scalafmtCheckAll ; scalafmtSbtCheck; serverTestProj/scalafmtCheckAll; headerCheck ;test:headerCheck ;whitesourceOnPush ;test:compile; publishLocal; test; serverTestProj/test; doc; $UTIL_TESTS; ++$SCALA_213; $UTIL_TESTS"
    - SBT_CMD="scripted actions/* apiinfo/* compiler-project/* ivy-deps-management/* reporter/* tests/* watch/* classloader-cache/* package/*"
    - SBT_CMD="scripted dependency-management/* plugins/* project-load/* java/* run/* nio/*"
    - SBT_CMD="repoOverrideTest:scripted dependency-management/*; scripted source-dependencies/* project/*"

matrix:
  fast_finish: true
  include:
    - env:
        - TRAVIS_JDK=adopt@1.8.0-222
        - SBT_CMD="++$SCALA_213; $UTIL_TESTS; ++$SCALA_212; $UTIL_TESTS; scripted actions/* source-dependencies/*1of3 dependency-management/*1of4 java/*"

before_install:
  - curl -sL https://raw.githubusercontent.com/shyiko/jabba/0.11.0/install.sh | bash && . ~/.jabba/jabba.sh

install:
  - $JABBA_HOME/bin/jabba install $TRAVIS_JDK
  - $JABBA_HOME/bin/jabba install openjdk@1.10
  - unset _JAVA_OPTIONS
  - export JAVA_HOME="$JABBA_HOME/jdk/$TRAVIS_JDK" && export PATH="$JAVA_HOME/bin:$PATH" && java -Xmx32m -version

script:
  # It doesn't need that much memory because compile and run are forked
  - sbt -Dsbt.io.virtual=false -Dsbt.ci=true -J-XX:ReservedCodeCacheSize=128m -J-Xmx800M -J-Xms800M -J-server "$SBT_CMD"

before_cache:
  - find $HOME/.cache/coursier/v1 -name "ivydata-*.properties" -delete
  - find $HOME/.ivy2              -name "ivydata-*.properties" -delete
  - find $HOME/.sbt               -name "*.lock"               -delete

cache:
  directories:
    - $HOME/.cache/coursier/v1
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.jabba
