dist: trusty

language: scala

env:
  global:
  - SBT_VER=1.1.1

matrix:
  include:
    ## build using JDK 8, test using JDK 8
    - script:
        - sbt -Dsbt.build.version=$SBT_VER universal:packageBin
        - cd citest && ./test.sh

    ## build using JDK 8, test using JDK 9
    - script:
        - sbt -Dsbt.build.version=$SBT_VER universal:packageBin
        - jdk_switcher use oraclejdk9
        - cd citest && ./test.sh

    ## build using JDK 8, test using JDK 10
    - script:
        - sbt -Dsbt.build.version=$SBT_VER universal:packageBin
        - citest/install-jdk10.sh
        - cd citest && ./test.sh

    - script:
        - sbt -Dsbt.build.version=$SBT_VER rpm:packageBin debian:packageBin
      addons:
        apt:
          packages:
            - fakeroot
            - rpm

scala:
  - 2.10.7

jdk:
  - oraclejdk8

# Undo _JAVA_OPTIONS environment variable
before_script:
  - _JAVA_OPTIONS=

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt  -name "*.lock"               -delete
