language: scala
jdk: oraclejdk8

scala:
  - 2.11.12
  - 2.12.4

matrix:
  include:
  - scala: 2.12.4
    jdk: oraclejdk9

script: sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M
  ++$TRAVIS_SCALA_VERSION
  mimaReportBinaryIssues
  scalafmt::test test:scalafmt::test sbt:scalafmt::test
  test
  packagedArtifacts # ensure that all artifacts for publish package without failure

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -delete
  - find $HOME/.sbt        -name "*.lock"               -delete
