# Adapted from https://github.com/sbt/sbt-native-packager/blob/master/appveyor.yml
version: '{build}'
os: Windows Server 2012
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\sbt" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'https://dl.bintray.com/sbt/native-packages/sbt/0.13.8/sbt-0.13.8.zip',
          'C:\sbt-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\sbt-bin.zip", "C:\sbt")
      }
  - cmd: SET PATH=C:\sbt\sbt\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET SBT_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - git submodule update --init --recursive
build_script:
  - sbt ++2.11.12 clean compile coreJVM/publishLocal
  - sbt ++2.10.7 clean compile
  - sbt ++2.12.4 coreJVM/publishLocal cache/publishLocal cli/publishLocal extra/publishLocal sbt-shared/publishLocal
  - sbt ++2.10.7 coreJVM/publishLocal cache/publishLocal extra/publishLocal sbt-shared/publishLocal
test_script:
  - ps: Start-Job -filepath .\scripts\start-it-auth-server.ps1 -ArgumentList $pwd
  - ps: Start-Sleep -s 15 # wait for the first server to have downloaded its dependencies
  - ps: Start-Job -filepath .\scripts\start-it-no-listing-server.ps1 -ArgumentList $pwd
  - sbt ++2.12.4 testsJVM/test testsJVM/it:test # Would node be around for testsJS/test?
  - sbt ++2.11.12 testsJVM/test testsJVM/it:test
  - sbt ++2.10.7 testsJVM/test testsJVM/it:test
  - sbt ++2.12.4 "sbt-coursier/scripted sbt-coursier/simple" sbt-coursier/publishLocal "sbt-shading/scripted sbt-shading/*" # for sbt 1.0
  - sbt ++2.10.7 "sbt-coursier/scripted sbt-coursier/*" "sbt-coursier/scripted sbt-coursier-0.13/*" sbt-coursier/publishLocal "sbt-shading/scripted sbt-shading/*" "sbt-shading/scripted sbt-shading-0.13/*" # for sbt 0.13
branches:
  only:
    - master
