# Adapted from https://github.com/sbt/sbt-native-packager/blob/master/appveyor.yml
version: '{build}'
os: Windows Server 2012
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\sbt" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'https://dl.bintray.com/sbt/native-packages/sbt/0.13.8/sbt-0.13.8.zip',
          'C:\sbt-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\sbt-bin.zip", "C:\sbt")
      }
  - cmd: SET PATH=C:\sbt\sbt\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET SBT_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - git submodule update --init --recursive
  - ps: |
      if (!(Test-Path 'C:\Users\appveyor\.ivy2\local\sandbox\sandbox_native0.3_2.11\0.1-SNAPSHOT')) {
        iex 'git clone https://github.com/coursier/scala-native'
        Set-Location -Path scala-native
        iex 'git checkout 550bf6e37d27'
        iex 'sbt ++2.11.8 sandbox/publishLocal'
        iex 'git checkout f8088aef6981'
        iex 'sbt ++2.11.8 nscplugin/publishLocal util/publishLocal nir/publishLocal tools/publishLocal'
        Set-Location -Path ..
      }
  - ps: |
      if (!(Test-Path 'C:\Users\appveyor\.m2\repository\org\anarres\jarjar\jarjar-core\1.0.1-coursier-SNAPSHOT')) {
        iex 'git clone https://github.com/alexarchambault/jarjar'
        Set-Location -Path jarjar
        iex 'git checkout 249c8dbb970f8'
        iex './gradlew.bat :jarjar-core:install'
        Set-Location -Path ..
      }
build_script:
  - sbt ++2.11.11 clean compile coreJVM/publishLocal cli/publishLocal
  - sbt ++2.12.1 http-server/publishLocal
  - sbt ++2.10.6 clean compile
  - sbt ++2.12.1 coreJVM/publishLocal cache/publishLocal extra/publishLocal # to make the scripted sbt 1.0 tests happy
  - sbt ++2.10.6 coreJVM/publishLocal cache/publishLocal extra/publishLocal # to make the scripted sbt 0.13 tests happy
test_script:
  - ps: Start-Job -filepath .\scripts\start-it-auth-server.ps1 -ArgumentList $pwd
  - ps: Start-Sleep -s 15 # wait for the first server to have downloaded its dependencies
  - ps: Start-Job -filepath .\scripts\start-it-no-listing-server.ps1 -ArgumentList $pwd
  - sbt ++2.12.1 testsJVM/test testsJVM/it:test # Would node be around for testsJS/test?
  - sbt ++2.11.11 testsJVM/test testsJVM/it:test
  - sbt ++2.10.6 testsJVM/test testsJVM/it:test
  - sbt ++2.12.1 "sbt-coursier/scripted sbt-coursier/simple" sbt-coursier/publishLocal "sbt-shading/scripted sbt-shading/*" # for sbt 1.0
  - sbt ++2.10.6 "sbt-coursier/scripted sbt-coursier/*" "sbt-coursier/scripted sbt-coursier-0.13/*" sbt-coursier/publishLocal "sbt-shading/scripted sbt-shading/*" "sbt-shading/scripted sbt-shading-0.13/*" # for sbt 0.13
cache:
  - '%USERPROFILE%\.ivy2\cache'
  - '%USERPROFILE%\.m2'
  - '%USERPROFILE%\.sbt'
  - '%USERPROFILE%\.coursier'
branches:
  only:
    - master
