# Adapted from https://github.com/sbt/sbt-native-packager/blob/master/appveyor.yml
version: '{build}'
os: Windows Server 2012
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\sbt" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'https://dl.bintray.com/sbt/native-packages/sbt/0.13.8/sbt-0.13.8.zip',
          'C:\sbt-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\sbt-bin.zip", "C:\sbt")
      }
  - cmd: SET PATH=C:\sbt\sbt\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET SBT_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: SET COURSIER_NO_TERM=1
build_script:
  - sbt ++2.11.8 clean compile coreJVM/publishLocal
  - sbt ++2.10.6 clean compile
test_script:
  - sbt ++2.11.8 testsJVM/test # Would node be around for testsJS/test?
  - sbt ++2.10.6 testsJVM/test
cache:
  - C:\sbt\
  - C:\Users\appveyor\.ivy2
  - C:\Users\appveyor\.sbt
